- hosts: myweb
  tasks:
  - name: "Install httpd package"
    package:
        name: "httpd"
        state: present

  - name: "Install php package"
    package:
        name: "php"
        state: present


  - name: "Copying webpage"
    template:
       src: index.php
       dest: "/var/www/html/index.php"

  - name: "Start web-service"
    service:
          name: "httpd"
          state: restarted

- hosts: mylb
  tasks:
  - name: "Install Haproxy"
    package: 
       name: "haproxy"
       state: present

  - template: 
       src: "haproxy.cfg.j2"
       dest: "/etc/haproxy/haproxy.cfg"

  - service:
       name: "haproxy"
       state: restarted
       



